version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      angular:
        patterns:
          - "@angular/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/js"
      patch:
        update-types:
          - "patch"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
      - "area:ci"
    open-pull-requests-limit: 100
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100
