name: "Bug Report 🐛"
description: Report a bug encountered while operating Netzgrafik-Editor
labels: []
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Before reporting a bug, please ensure that:
        - Your problem is not already reported (access the list [here](https://github.com/OpenRailAssociation/netzgrafik-editor-frontend/issues?q=is%3Aissue%20state%3Aopen%20type%3ABug))
        - Your problem is not already fixed on the `main` branch, if you are able to check

  - type: dropdown
    id: input
    attributes:
      label: What is the input mode?
      multiple: false
      options:
        - Mouse
        - Touchpad
        - Other
      default: 0

  - type: dropdown
    id: type
    attributes:
      label: What type of issue is it?
      multiple: true
      options:
        - Functionality
        - Accessibility
        - Performance
        - Security vulnerability
        - Other
      default: 0

  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Please provide as much information as possible. Not doing so may result in your bug not being addressed in a timely manner.
        Screenshots and videos are very useful.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: repro
    attributes:
      label: How can we reproduce it (as minimally and precisely as possible)?
      placeholder: |
        💡 When specific data is involved, providing a Netzgrafik JSON export can help a lot to reproduce quickly and precisely.
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: On which environments the bug occurs?
      multiple: true
      options:
        - Local
        - Intern (SBB)
        - GitHub pages demo
        - Flatland
        - Embedded (like in OSRD)
        - Custom (Docker compose)
        - Other
      default: 0

  - type: dropdown
    id: browser
    attributes:
      label: On which browser the bug occurs?
      multiple: true
      options:
        - Firefox
        - Google Chrome
        - Microsoft Edge
        - Safari
        - Opera
        - Other
      default: 0

  - type: input
    id: ngeVersion
    attributes:
      label: Netzgrafik-Editor version (top left corner `Version x.yy.zz`)
      placeholder: "2.10.9"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        If you're already a member of the repo, add a label about the bug severity, by adding one of a following labels:
        - `bug:minor` (the impacted functionality is still usable)
        - `bug:major` (the impacted functionality is hardly usable)
        - `bug:critical` (the impacted functionality is not usable at all)
        Also, if you are a user of Netzgrafik-Editor, adding the label `from-user` might help to prioritize fixing this bug.
