name: "Feature Request"
description: Request of a new feature or enhancement of a new one
labels: ["feature-request"]
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make Netzgrafik-Editor evolve!
        Before requesting a new feature, please ensure that your idea is not already requested (access the list [here](https://github.com/OpenRailAssociation/netzgrafik-editor-frontend/issues?q=is%3Aissue%20label%3A%22feature-request%22)).

  - type: dropdown
    id: audience
    attributes:
      label: Who would benefit from this feature?
      multiple: true
      options:
        - Users
        - Developers

  - type: textarea
    id: abilities
    attributes:
      label: What is this feature about?
      value: |
        - adding a new way to create ...
        - making ... able to be displayed on the network graph
        - making ... data model evolve
        - (also, mock-ups or screenshots highly help to apprehend a new feature or concept)
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Why is this feature valuable?
      value: |
        This feature matters because it:
        - enables ...
        - will make ... easier
        If this feature is not accepted, this would compromise:
        - this feature ...
        - or this use case ...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        If you are a user of Netzgrafik-Editor, adding the label `from-user` might help to prioritize fixing this bug.
